# https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/

# also a Deployment example in
# https://github.com/kubernetes/examples/blob/master/guestbook/redis-master-deployment.yaml


# CHANGE LIST
# added metadata to match the redis-pod.yaml file
# Do I need to change .spec.ports.port etc?
# Change .apiVersion ?


apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis